# Stage 1: 開発ステージ
FROM node:latest AS development-stage

# プロジェクトディレクトリの作業ディレクトリを設定
WORKDIR /app

# プロジェクトの依存関係のインストール
COPY /frontend/package.json .
RUN npm install @vue/cli

# プロジェクトファイルのコピー
COPY /frontend/ .

# 開発用サーバーの起動
CMD ["npm", "run", "serve"]
