# Use Node.js image as a base
FROM node:latest

# Set the working directory inside the container
WORKDIR /app

RUN rm -rf node_modules

# Install Vue CLI globally
RUN npm install -g @vue/cli

# Copy package.json and package-lock.json
COPY /frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy all files from the current directory to the working directory inside the container
COPY /frontend/ .

# Command to run the Vue.js app
CMD ["npm", "run", "serve"]
