source "https://rubygems.org"

ruby "3.0.3"

gem "rails", "~> 7.1.3", ">= 7.1.3.2"

# DBアダプタ
gem "mysql2", "~> 0.5"

# WEBサーバー
gem "puma", ">= 5.0"

# Crossドメイン（API通信をするために必要）
gem 'rack-cors'


gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ]
end

group :development do
end
